default: &default
  docker:
  - image: choerodon/cifront:0.5.0

version: 2
jobs:
  node_build_dev:
    <<: *default

    working_directory: ~/repo
    environment:
      CI_PROJECT_PATH: $CIRCLE_PROJECT_REPONAME
    
    steps:
      - checkout
      - run: git submodule update --init
      - run: |
            python ./boot/structure/configAuto.py iam
            chmod a+x ./boot/structure/moduleCi.sh
            ./boot/structure/moduleCi.sh boot iam
      - run: |
            cd boot
            ./node_modules/.bin/gulp start
            npm run devbuild

  node_build:
    <<: *default

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init
      - run: |
            python ./boot/structure/configAuto.py iam
            chmod a+x ./boot/structure/moduleCi.sh
            cd boot && npm install choerodon-ui -S  && cd ..
            ./boot/structure/moduleCi.sh boot iam
      - run: |
            cd boot
            ./node_modules/.bin/gulp start
            npm run build
          
      - persist_to_workspace:
          root: .
          paths:
            - boot/dist

  docker_build:
    <<: *default
    steps:
      - setup_remote_docker:
            version: 17.05.0-ce
      - checkout
      - attach_workspace:
          at: .
      - run: |
          sed -i "/s/registry.cn-hangzhou.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
          export CI_COMMIT_TAG=$CIRCLE_TAG
          docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
          docker build --pull -t ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG}
          docker push ${DOCKER_GROUP_NAME}/${CIRCLE_PROJECT_REPONAME}:${CI_COMMIT_TAG}

workflows:
  version: 2
  release:
    jobs:
      - node_build:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
      - docker_build:
          context: org-global
          requires:
          - node_build
          filters:
            tags:
              only: /^.*/
            branches:
              only:
                - /^release-.*$/
                - /^hotfix-.*$/
  daily:
    jobs:
      - node_build_dev:
          context: org-global
          filters:
            branches:
              only: 
               - /^.*$/